import os
import re
import google.generativeai as genai
from e2b import Sandbox

genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
MODEL_NAME = 'models/gemini-2.5-flash-lite'

def get_ai_code(prompt):
    model = genai.GenerativeModel(MODEL_NAME)
    full_prompt = (
        "Write Python code to solve the task. Code only. Do not use markdown. "
        f"Task: {prompt}"
    )
    response = model.generate_content(full_prompt)
    return re.sub(r"```python|```", "", response.text).strip()

def main():
    print("📊 Starting Data Analytics Agent")
    
    # We instruct the AI to physically create a file
    prompt = (
        "1. Create a pandas DataFrame with 5 rows of dummy sales data (Columns: Item, Price). "
        "2. Save this DataFrame to a CSV file named 'sales_report.csv'. "
    )
    
    print("🧠 Generating code...")
    code = get_ai_code(prompt)
    
    print("🚀 Starting Sandbox...")
    sandbox = Sandbox.create()
    
    # Pre-install pandas so the AI's code doesn't fail
    print("📦 Installing pandas library...")
    sandbox.commands.run("pip install pandas")
    
    sandbox.files.write("data_script.py", code)
    
    print("⚙️ Running AI data script...")
    sandbox.commands.run("python data_script.py")
    
    print("⬇️ Extracting generated 'sales_report.csv' from the cloud...")
    try:
        # Read the file generated by the AI from the remote sandbox
        csv_content = sandbox.files.read("sales_report.csv")
        
        # Save it to your local Mac
        with open("downloaded_sales_report.csv", "w") as f:
            f.write(csv_content)
            
        print("✅ Success! The file has been downloaded to your Mac.")
        print(f"\n--- File Preview ---\n{csv_content}")
        
    except Exception as e:
        print(f"❌ Failed to find or download the file: {e}")

    sandbox.kill()

if __name__ == "__main__":
    main()
